# Generated by Django 4.2.13 on 2024-05-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshiphub_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='Deadline',
            new_name='deadline',
        ),
    ]
