# Generated by Django 4.2.13 on 2024-05-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshiphub_api', '0002_rename_deadline_scholarship_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='scholarship',
            new_name='scholarship_id',
        ),
    ]
